### ISSUE TITLE
Server error, status code: 502, error code: 10001, message: Service broker error: 

### ISSUE THREAD

**Issue by yogendramummaneni** [codedellemc/ecs-cf-service-broker#80]
# cf create-service gstools-ecs-cluster 5gb yogi-test-ecs
Creating service instance yogi-test-ecs in org PsAppsOrg / space PsApps-Tst as mummay...
FAILED
Server error, status code: 502, error code: 10001, message: Service broker error: com.emc.object.s3.S3Exception: could not parse error response

It seems the below are the log messages from the broker app when this happened:

2017-08-31T13:54:56.756+01:00 [APP/PROC/WEB/0] [OUT] 1 < Server: Apache/2.4.6 (Red Hat Enterprise Linux) OpenSSL/1.0.1e-fips
2017-08-31T13:54:56.756+01:00 [APP/PROC/WEB/0] [OUT] 1 < Keep-Alive: timeout=5, max=100
2017-08-31T13:54:56.756+01:00 [APP/PROC/WEB/0] [OUT] 1 < Connection: Keep-Alive
2017-08-31T13:54:56.756+01:00 [APP/PROC/WEB/0] [OUT] 1 < Content-Length: 0
2017-08-31T13:54:56.756+01:00 [APP/PROC/WEB/0] [OUT] 1 < Content-Type: application/xml
2017-08-31T13:54:56.756+01:00 [APP/PROC/WEB/0] [OUT] 1 < Date: Thu, 31 Aug 2017 12:54:56 GMT
2017-08-31T13:54:57.798+01:00 [APP/PROC/WEB/0] [OUT] 2017-08-31 12:54:57.797 WARN 14 --- [nio-8080-exec-5] com.emc.object.s3.jersey.RetryFilter : could not reset entity stream for retry: java.io.IOException: stream does not support mark/reset
2017-08-31T13:55:02.478+01:00 [APP/PROC/WEB/0] [OUT] 1 > POST https://10.146.81.100:4443/object/bucket/ecs-cf-broker-2f41431b-68a1-43e4-b9ab-0857ababdb3b/deactivate?namespace=ns1
2017-08-31T13:55:02.478+01:00 [APP/PROC/WEB/0] [OUT] 1 > X-SDS-AUTH-TOKEN: BAAcK1RWU2Q3M2VKKzVmWjFEemVzZXg3VlN3YzJrPQMAjAQASHVybjpzdG9yYWdlb3M6VmlydHVhbERhdGFDZW50ZXJEYXRhOjk3YTBiM2JiLTJjMGItNDZiOS1hMDBkLTRhMDI1YzM1MTQ2YwIADTE1MDQxNzM3NzA5OTMDAC51cm46VG9rZW46MzUyMjljZDAtNzg3YS00YjMzLTgzMTctZjVjNDI2MzQ4NTgzAgAC0A8=

The same error also happened when we tried bind an app to ecs serivce

Could not bind to service titan-upload-ecs
Error: Server error, status code: 502, error code: 10001, message: Service broker error: could not parse error response

**Comment by spiegela** [comment]
@yogendramummaneni I think perhaps either the `object-endpoint` or `repository-endpoint` parameter is pointing to port `4443` rather than `9020`/`9021` for `http` or `https`, respectively. If you can provide your `application.yml` and the broker environment variables, I can validate the configuration.

FYI, if your ECS platform has a *Base URL* configured with DNS, you can use the `base-url` parameter instead of `object-endpoint` to automatically detect it.

**Comment by yogendramummaneni** [comment]
[application.yml.txt](https://github.com/codedellemc/ecs-cf-service-broker/files/1269751/application.yml.txt)
Thanks for the reply @spiegela 

object-endpoint is pointing to port 9020 only.
Here I am attaching our application.yml file



This is LB config:

<VirtualHost *:80>

        <Proxy balancer://ecsobject>
                BalancerMember  http://stg-ecsnode01:9020
                BalancerMember  http://stg-ecsnode02:9020
                BalancerMember  http://stg-ecsnode03:9020
                BalancerMember  http://stg-ecsnode04:9020
                ProxySet        lbmethod=bytraffic
        </Proxy>

        ProxyPreserveHost On
        ProxyPass / balancer://ecsobject/
        ProxyPassReverse / balancer://ecsobject/

</VirtualHost>

We don't have DNS configured for ECS, we are just using LB's IP address.

**Comment by spiegela** [comment]
This looks like an error writing to the repository bucket. Can you take a look at the ACLs of the `ecs-cf-broker-repository` bucket? If there isn't anything apparent there, you may need to open a case so that we can enabled the detailed S3 logging on the ECS nodes.

**Comment by yogendramummaneni** [comment]
Hi @spiegela It seems that the bucket (ecs-cf-broker-2f41431b-68a1-43e4-b9ab-0857ababdb3b) creation as part of the service instance creation was failed, I can't see this bucket exist in the buckets repository at all.

Thanks,
Yogi.

**Comment by yogendramummaneni** [comment]
Today again we are seeing the same error multiple times.

I believe these are the broker app error when the issue occured:
2017-09-13T08:04:51.47+0100 [APP/PROC/WEB/0] OUT <error>
   2017-09-13T08:04:51.47+0100 [APP/PROC/WEB/0] OUT     <code>10001</code>
   2017-09-13T08:04:51.47+0100 [APP/PROC/WEB/0] OUT     <description>An error occurred while encoding/decoding of tokens</description>
   2017-09-13T08:04:51.47+0100 [APP/PROC/WEB/0] OUT     <details>Unable to decode token.</details>
   2017-09-13T08:04:51.47+0100 [APP/PROC/WEB/0] OUT     <retryable>false</retryable>
   2017-09-13T08:04:51.47+0100 [APP/PROC/WEB/0] OUT </error>

In another instance:
=============
2017-09-13T10:20:46.55+0100 [RTR/0]      OUT gstools-ecs-cluster-broker.cfcq.isus.emc.com - [2017-09-13T09:20:41.327+0000] "PUT /v2/service_instances/400eac13-81f5-4046
-9cec-e7443ed7c454/service_bindings/3ea64ed9-51b3-458b-8fb5-e5725d04538a HTTP/1.1" 500 220 48 "-" "HTTPClient/1.0 (2.7.1, ruby 2.3.1 (2016-04-26))" "xx.xx.xx.xx:54516"
 "xx.xx.xx.xx:63369" x_forwarded_for:"xx.xx.xx.xx, xx.xx.xx.xx" x_forwarded_proto:"http" vcap_request_id:"a8626ede-56d8-46f1-56d4-b00004e132ce" response_time:5.225
895498 app_id:"e2ea03e7-26f8-41ac-8632-fa8b11f1afce" app_index:"0" x_b3_traceid:"11a9f39aabea2e28" x_b3_spanid:"11a9f39aabea2e28" x_b3_parentspanid:"-"
2017-09-13T10:20:46.55+0100 [APP/PROC/WEB/0]OUT 2017-09-13 09:20:46.553  WARN 14 --- [nio-8080-exec-9] com.emc.object.s3.jersey.RetryFilter     : could not reset entity
 stream for retry: java.io.IOException: stream does not support mark/reset


There are many java.io.IOException errors there in vnest-error.log and vnest.log log files.
From one of the ECS nodes:
2017-09-13T09:17:59,011 [ForkJoinPool-COMMUNICATOR-worker-755] ERROR  RemoteOperationProcessor.java (line 303) get exception when process remote request.
com.emc.storageos.data.object.exception.ObjectControllerException: ERROR_COMM_SERVER_UNAVAILABLE
        at com.emc.storageos.data.object.communicator.impl.RemoteDataNodeCommunicator.transmitUsingRandomSocket(RemoteDataNodeCommunicator.java:575)
        at com.emc.storageos.data.object.communicator.impl.RemoteDataNodeCommunicator.enqueueAndSend(RemoteDataNodeCommunicator.java:250)
        at com.emc.storageos.data.object.communicator.impl.RemoteOperationProcessor$RequestProcessor.run(RemoteOperationProcessor.java:295)
        at com.emc.storageos.data.object.communicator.impl.RemoteOperationProcessor$RequestProcessor.run(RemoteOperationProcessor.java:256)
        at co.paralleluniverse.fibers.Fiber.run(Fiber.java:1027)
        at com.emc.storageos.data.object.ViprFiber.run(ViprFiber.java:43)
        at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1022)
        at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:732)
        at co.paralleluniverse.fibers.FiberForkJoinScheduler$FiberForkJoinTask.exec1(FiberForkJoinScheduler.java:265)
        at co.paralleluniverse.concurrent.forkjoin.ParkableForkJoinTask.doExec(ParkableForkJoinTask.java:117)
        at co.paralleluniverse.concurrent.forkjoin.ParkableForkJoinTask.exec(ParkableForkJoinTask.java:74)
        at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:261)
        at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:988)
        at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
        at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.io.IOException: Broken connection to /10.146.81.101:1298
        at com.emc.storageos.data.object.communicator.impl.CommunicatorSenderSocket.write(CommunicatorSenderSocket.java:524)
        at com.emc.storageos.data.object.communicator.impl.RemoteDataNodeCommunicator.transmitUsingRandomSocket(RemoteDataNodeCommunicator.java:562)
        ... 14 more
2017-09-13T09:18:25,617 [ReceiverSocketThread-10.146.81.101:45198-325133] ERROR  RemoteDataNodeCommunicator.java (line 1044) socket for 10.146.81.101 broken

@spiegela Could you help us in enabling the detailed logging?

**Comment by spiegela** [comment]
@yogendramummaneni Sorry for the delay responding. I'm not sure how I missed the mentions. Let's find sometime to troubleshoot live next week.

**Comment by yogendramummaneni** [comment]
Thanks @spiegela, please let me know when it suits to you.

**Comment by yogendramummaneni** [comment]
It seems the issue was due to the port 9020 has not been listening on couple of nodes on ECS cluster as the rpcbind is preventing to start the 9020 port. After stopping the rpcbind service, the port 9020 started listening. Not seeing this issue any more at least since the 9020 port is listening on all nodes.
