### ISSUE TITLE
 java.security.cert.CertificateException: No subject alternative names matching IP address 172.31.4.11 found

### ISSUE THREAD

**Issue by roninby** [codedellemc/ecs-cf-service-broker#81]
Hello,

I'm trying to start a demo ECS service broker which backed by a single-node ECS, the ECS node has been built following the default procedure of [ECS-CommunityEdition Standard Installation](https://github.com/EMCECS/ECS-CommunityEdition/blob/master/docs/source/installation/ECS-Installation.md), which is using a self-signed certificate.

The ECS service broker failed to startup, the command `gradlew bootRun` failed after  the config file `src/main/resources/application.yaml`  was modified to point to the single ECS node. The error message is attached at the end of this post, it should be a certificate error.

I noticed the ECS service broker supports self-signed certificate when providing a PEM formatted certificate file named `localhost.pem` into the `src/main/resources` directory.  However, does it indicate the broker has to be installed on the ECS node? If the ECS service broker will be pushed to Cloud Foundry later, how to config the SSL certificate, then?

Thanks in advance.

**The Error log of `gradlew bootRun`**:

2017-10-10 08:51:20.612  INFO 11924 --- [           main] c.e.e.c.broker.config.Application        : Instantiating unencrypted esc connection
2017-10-10 08:51:21.777  WARN 11924 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'serviceInstanceController' defined in URL [jar:file:/home/gcps/.gradle/caches/modules-2/files-2.1/org.springframework.cloud/spring-cloud-cloudfoundry-service-broker/1.0.1.RELEASE/f97084116128362e5c71ccc22e459979621bd2cd/spring-cloud-cloudfoundry-service-broker-1.0.1.RELEASE.jar!/org/springframework/cloud/servicebroker/controller/ServiceInstanceController.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ecsServiceInstanceService': Unsatisfied dependency expressed through field 'ecs'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ecsService': Invocation of init method failed; nested exception is javax.ws.rs.ProcessingException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative names matching IP address 172.31.4.11 found
2017-10-10 08:51:21.849  INFO 11924 --- [           main] utoConfigurationReportLoggingInitializer :

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-10-10 08:51:21.881 ERROR 11924 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'serviceInstanceController' defined in URL [jar:file:/home/gcps/.gradle/caches/modules-2/files-2.1/org.springframework.cloud/spring-cloud-cloudfoundry-service-broker/1.0.1.RELEASE/f97084116128362e5c71ccc22e459979621bd2cd/spring-cloud-cloudfoundry-service-broker-1.0.1.RELEASE.jar!/org/springframework/cloud/servicebroker/controller/ServiceInstanceController.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ecsServiceInstanceService': Unsatisfied dependency expressed through field 'ecs'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ecsService': Invocation of init method failed; nested exception is javax.ws.rs.ProcessingException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative names matching IP address 172.31.4.11 found
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:189) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1193) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1095) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
        at org.springframework.beans.factoort.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.5.1.RELEASE.j1.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.1.RELEASE.jar:1.5.1.RELEASE]
        at com.emc.ecs.cloudfoundry.broker.config.Application.main(Application.java:44) [main/:na]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ecsServiceInstanceService': Unsatisfied dependency expressed through field 'ecs'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ecsService': Invocation of init method failed; nested exception is javax.ws.rs.ProcessingException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative names matching IP address 172.31.4.11 found

**Comment by spiegela** [comment]
The broker can work using the self-signed cert that is installed on the node by default, even if it is running as a CF app. The error indicates that the self-signed certificate hasn't been imported into the broker, so I am guessing that it's picking up a sample cert from the repo (since the error is referring to host verification).

You can download the cert from the ECS node and convert to PEM format by either Firefox (there are options to export as PEM when you view the cert) or OpenSSL. To use OpenSSL, here is the command that I typically use:

```
openssl s_client -servername ECS_IP -connect ECS_IP:443 \
    </dev/null 2>/dev/null | openssl x509 -text
```

**Comment by roninby** [comment]
@spiegela, thanks for the quick response.

I've downloaded the cert from ECS node, now the ECS service broker app can be successfully started on the ECS node or on another host. Will try to push it as a CF app sometime later.

Now, I got stuck when registering a service broker using `create-service-broker` as below, I tried several different accounts, but still failed, same error with login to http://172.31.4.11:8080. Is there any specific account for ECS broker authentication?

```
[gcps@ansiblehost work]$ cf create-service-broker ecs-broker ecs-cf-broker-user zG4iwBEkrHJOMCCnVLvZfbjYe/+a3r9FHDJgY0pD http://172.31.4.11:8080
Creating service broker ecs-broker as admin...
FAILED
Server error, status code: 502, error code: 10001, message: Authentication with the service broker failed. Double-check that the username and password are correct: http://172.31.4.11:8080/v2/catalog

[gcps@ansiblehost work]$ cf create-service-broker ecs-broker admin xxxxxxxx http://172.31.4.11:8080
Creating service broker ecs-broker as admin...
FAILED
Server error, status code: 502, error code: 10001, message: Authentication with the service broker failed. Double-check that the username and password are correct: http://172.31.4.11:8080/v2/catalog

[gcps@ansiblehost work]$ cf create-service-broker ecs-broker root xxxxxxxx http://172.31.4.11:8080
Creating service broker ecs-broker as admin...
FAILED
Server error, status code: 502, error code: 10001, message: Authentication with the service broker failed. Double-check that the username and password are correct: http://172.31.4.11:8080/v2/catalog

```

Thanks again.

**Comment by roninby** [comment]
@spiegela , 

According to your [video](https://blog.thecodeteam.com/2016/01/05/emc-ecs-with-cloud-foundry/),  after removing the prefix of the username, the service broker is registered finally. 
```
[gcps@ansiblehost work]$ cf create-service-broker ecs-broker user zG4iwBEkrHJOMCCnVLvZfbjYe/+a3r9FHDJgY0pD http://172.31.4.11:8080
Creating service broker ecs-broker as admin...
OK
```
Thanks for your instructions.

**Comment by roninby** [comment]
After changing the endpoint link from `localhost` to its IP address in `application.yml`,  the service is created now. 
[application.yml.txt](https://github.com/codedellemc/ecs-cf-service-broker/files/1373983/application.yml.txt)

Thanks for your help.
